name: validate-unattended
description: Validate Unattended installer
branding:
  icon: "command"
  color: "blue"
runs:
  using: docker
  image: 'wazuh/debian-bullseye-unattended-base:latest'
  entrypoint: '/entrypoint.sh'



